name: microphone_stream
description: A new flutter plugin project.
version: 0.0.5
author: Andrew Ackerman <andrew@canaryspeech.com>
homepage: https://github.com/andrewackerman/flutter_microphone_stream.git

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.andrewackerman.microphonestream
    pluginClass: MicrophoneStreamPlugin